export const ADD_LINK = 'ADD_LINK';
export const USER_LOGOUT = 'USER_LOGOUT';
export const ADD_ENTITY ='ADD_ENTITY';
export const ADD_TAG ='ADD_TAG';
export const STORE_PENDING_ENTITIES = 'STORE_PENDING_ENTITIES';
export const STORE_ENTITIES = 'STORE_ENTITIES';
export const STORE_SOURCES = 'STORE_SOURCES';
export const STORE_PROJECTS = 'STORE_PROJECTS';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';

